import Head from "next/head";
import { Inter } from "next/font/google";
import Choose from "@/components/choose";
import Services from "@/components/services";
import { useRouter } from 'next/router';


import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  const router = useRouter();
  const hireUsButtonClicked = () => {
    router.push('/contact');
  };
  
  return (
    <>
      <Head>
        <title>Johns Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[url('/image/bg-17.jpg')] bg-cover bg-center">
        <div className="">
          <section className="text-center m-auto pt-60 pb-40 max-w-screen-lg">
            <p className="text-white text-7md font-bold"> IT `S YOUR DREAM</p>
            <p className="text-yellow-400 text-md font-bold">We Are Building</p>
            <p className="text-yellow-400 text-md font-bold">
              We Are Constructing
            </p>
            <p className="text-yellow-400 text-md font-bold">We Are Planning</p>
          </section>
          <section className="bg-yellow-400 text-lg font-semibold flex justify-between p-4 sm:max-md:flex flex-wrap">
            <p>Looking for best partner for your next Renovations?</p>
            <button onClick={hireUsButtonClicked}className="border-solid border-2 border-black p-2 ">
              Hire us Now
            </button>
          </section>
          <section className="bg-white lg:grid grid-cols-3 justify-items-stretch whitespace-normal pr-8 py-20 sm:max-sm:grid-rows-3 pl-8 ">
            <div className="font-bold text-4xl whitespace-nowrap pr-5 sm:max-sm:row-span-1">
              Who We Are
              <span className="h-2 bg-yellow-400 w-50 mt-30 block"></span>
            </div>

            <div className="pr-4 sm:max-sm:row-span-2">
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem
              accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
              quae ab illo inventore veritatis et quasi architecto beatae. Sed
              ut perspiciatis unde omnis iste natus error sit voluptatem
              accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
              quae ab illo inventore veritatis et quasi architecto beatae.
            </div>

            <div className="air sm:max-sm:row-span-1">
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem
              accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
              quae ab illo inventore veritatis et quasi architecto beatae. Sed
              ut perspiciatis unde omnis iste natus error sit voluptatem
              accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
              quae ab illo inventore veritatis et quasi architecto beatae.
            </div>
          </section>
          <section id="services">
            <Services />
            <Choose />
          </section>
        </div>
      </main>
    </>
  );
}
